using Microsoft.Extensions.Logging.Abstractions;
using Microsoft.Extensions.Options;
using PerfectWorldAgent.Vision;

// Iterative harness for the vision pipeline. Loads every screenshot from samples/ and
// every template from samples/.templates/, runs NameMatcher across all (sample, template)
// pairs, and prints a similarity matrix. Lets us tweak NameRegion / threshold / binarize
// settings without spinning up the full app.
//
// Usage:
//   cd "Perfect World Agent"
//   dotnet run --project tools/VisionSampleRunner

var repoRoot = FindRepoRoot();
var samplesDir = Path.Combine(repoRoot, "samples");
var templatesDir = Path.Combine(samplesDir, ".templates");

if (!Directory.Exists(samplesDir) || !Directory.Exists(templatesDir))
{
    Console.Error.WriteLine($"Missing samples or templates dir under {repoRoot}");
    return 1;
}

var samples = Directory.GetFiles(samplesDir, "*.jpg")
    .Select(p => (FileName: Path.GetFileName(p), Bytes: File.ReadAllBytes(p)))
    .ToArray();

var templates = Directory.GetFiles(templatesDir, "*.png")
    .ToDictionary(p => Path.GetFileNameWithoutExtension(p), File.ReadAllBytes);

Console.WriteLine($"Loaded {samples.Length} samples and {templates.Count} templates");
Console.WriteLine();

// Threshold 0 so the runner shows raw scores for every template instead of "-" for
// sub-threshold matches. Real callers use the default 0.6. No DI here so we pass
// NullLogger explicitly.
var matcher = new NameMatcher(NullLogger<NameMatcher>.Instance, matchThreshold: 0.0);

// Dump binarised templates and binarised sample regions side-by-side so we can eyeball
// what MatchTemplate is actually seeing.
var debugDir = Path.Combine(samplesDir, ".debug");
Directory.CreateDirectory(debugDir);
foreach (var (name, bytes) in templates)
{
    File.WriteAllBytes(Path.Combine(debugDir, $"template-{name}.png"), matcher.DebugBinarizeFullImage(bytes));
}
foreach (var (fileName, bytes) in samples)
{
    File.WriteAllBytes(Path.Combine(debugDir, $"sample-{Path.GetFileNameWithoutExtension(fileName)}.png"), matcher.DebugBinarizeNameRegion(bytes));
}
Console.WriteLine($"Binarised debug dumps in {debugDir}");
Console.WriteLine();

// Sanity check the LabelAgentAsync code path: regenerate templates via matcher.CropNameRegion
// from each character's sample (matching how the orchestrator harvests them in production),
// then re-run the matrix using THOSE templates. If the end-to-end pipeline is consistent,
// self-scores should still be 1.000.
var regenerated = samples
    .Where(s => TryCharacterFromFileName(s.FileName, out _))
    .GroupBy(s => CharacterFromFileName(s.FileName))
    .ToDictionary(g => g.Key, g => matcher.CropNameRegion(g.First().Bytes));

Console.WriteLine($"Regenerated {regenerated.Count} templates via matcher.CropNameRegion");
Console.WriteLine();

// Header
Console.Write($"{"sample",-50}  ");
foreach (var name in templates.Keys.OrderBy(s => s))
{
    Console.Write($"{Truncate(name, 12),12} ");
}
Console.Write("| best");
Console.WriteLine();
Console.WriteLine(new string('-', 50 + 14 * templates.Count + 25));

// One row per sample, one column per template
foreach (var (fileName, bytes) in samples)
{
    Console.Write($"{Truncate(fileName, 50),-50}  ");

    // Collect scores by running matcher per-template (so we get individual scores not
    // just the winner). Reuse internal pipeline by calling Match with a single-entry dict.
    var scores = new Dictionary<string, double>();
    foreach (var (name, tplBytes) in templates)
    {
        var result = matcher.Match(bytes, new Dictionary<string, byte[]> { [name] = tplBytes });
        scores[name] = result?.Score ?? double.NaN;
    }

    foreach (var name in templates.Keys.OrderBy(s => s))
    {
        var score = scores.TryGetValue(name, out var s) ? s : double.NaN;
        Console.Write(double.IsNaN(score) ? $"{"-",12} " : $"{score,12:F3} ");
    }

    var best = matcher.Match(bytes, templates);
    Console.Write(best is null ? "| (no match)" : $"| {best.Name} ({best.Score:F3})");
    Console.WriteLine();
}

// Second matrix: same samples, but templates regenerated by the matcher itself. Lets us
// catch mismatches between TemplateRegion and SearchRegion sizing (template must be < source).
Console.WriteLine();
Console.WriteLine("=== Re-run with matcher-regenerated templates ===");
Console.Write($"{"sample",-50}  ");
foreach (var name in regenerated.Keys.OrderBy(s => s))
{
    Console.Write($"{Truncate(name, 12),12} ");
}
Console.Write("| best");
Console.WriteLine();
Console.WriteLine(new string('-', 50 + 14 * regenerated.Count + 25));

foreach (var (fileName, bytes) in samples)
{
    Console.Write($"{Truncate(fileName, 50),-50}  ");
    var scores = new Dictionary<string, double>();
    foreach (var (name, tplBytes) in regenerated)
    {
        var result = matcher.Match(bytes, new Dictionary<string, byte[]> { [name] = tplBytes });
        scores[name] = result?.Score ?? double.NaN;
    }
    foreach (var name in regenerated.Keys.OrderBy(s => s))
    {
        var score = scores.TryGetValue(name, out var s) ? s : double.NaN;
        Console.Write(double.IsNaN(score) ? $"{"-",12} " : $"{score,12:F3} ");
    }
    var best = matcher.Match(bytes, regenerated);
    Console.Write(best is null ? "| (no match)" : $"| {best.Name} ({best.Score:F3})");
    Console.WriteLine();
}

// === Coordinate OCR pass ===
Console.WriteLine();
Console.WriteLine("=== CoordinateReader (Tesseract) ===");

var tessdataPath = Path.Combine(AppContext.BaseDirectory, "tessdata");
var coordOptions = Options.Create(new CoordinateReaderOptions { TessdataPath = tessdataPath });
using var coordReader = new TesseractCoordinateReader(coordOptions, NullLogger<TesseractCoordinateReader>.Instance);

// Dump the preprocessed coord regions to the debug dir so we can eyeball what Tesseract
// is being asked to read.
foreach (var (fileName, bytes) in samples)
{
    var stem = Path.GetFileNameWithoutExtension(fileName);
    try
    {
        File.WriteAllBytes(Path.Combine(debugDir, $"coords-raw-{stem}.png"), coordReader.DebugCrop(bytes));
        File.WriteAllBytes(Path.Combine(debugDir, $"coords-mask-{stem}.png"), coordReader.DebugBinarize(bytes));
    }
    catch (Exception ex)
    {
        Console.WriteLine($"  preprocess failed for {fileName}: {ex.Message}");
    }
}

Console.WriteLine($"{"sample",-50}  result");
Console.WriteLine(new string('-', 75));
foreach (var (fileName, bytes) in samples)
{
    var coords = coordReader.Read(bytes);
    Console.WriteLine($"{Truncate(fileName, 50),-50}  {(coords is null ? "(no match)" : coords.ToString())}");
}

return 0;

static string Truncate(string s, int max) => s.Length <= max ? s : s[..max];

static bool TryCharacterFromFileName(string fileName, out string character)
{
    // Filename convention: "{world|word}-{Character}-{situation}.jpg"
    var parts = Path.GetFileNameWithoutExtension(fileName).Split('-');
    if (parts.Length >= 2)
    {
        character = parts[1];
        return true;
    }
    character = string.Empty;
    return false;
}

static string CharacterFromFileName(string fileName) =>
    TryCharacterFromFileName(fileName, out var c) ? c : throw new ArgumentException(fileName);

static string FindRepoRoot()
{
    var dir = new DirectoryInfo(AppContext.BaseDirectory);
    while (dir is not null && !File.Exists(Path.Combine(dir.FullName, "PerfectWorldAgent.slnx")))
    {
        dir = dir.Parent;
    }
    return dir?.FullName ?? throw new InvalidOperationException("Could not locate repo root.");
}
