stateDiagram-v2
	Hold --> Follow : GoFollow
	Hold --> Combat : GoCombat
	Hold --> Hold : Stop / Function
	Hold --> Hold : GoHold
	Hold --> Hold : CombatFinished
	Follow --> Hold : GoHold
	Follow --> Combat : GoCombat
	Follow --> Hold : Stop
	Follow --> Follow : GoFollow
	Follow --> Follow : CombatFinished
	Combat --> Hold : GoHold
	Combat --> Hold : CombatFinished
	Combat --> Hold : Stop
	Combat --> Combat : GoFollow
	Combat --> Combat : GoCombat
[*] --> Hold